### ISSUE TITLE
Why --phpfpm.fix-process-count?

### ISSUE THREAD

**Issue by dmamchyts** [hipages/php-fpm_exporter#232]
Hi,
Looks like issue https://bugs.php.net/bug.php?id=76003 already fixed (I haven't checked yet).
You can update README.md and default value

**Comment by itcsoft54** [comment]
phpfpm are ne use only with php8.0 or newer. Patch are for php8.0.

In add from version of php 8.1, openmetric are available without additionnal external exporter.

Change default create breaking change for version older than php 8.0

**Comment by dmamchyts** [comment]
***In add from version of php 8.1, openmetric are available without additionnal external exporter.
What you mean under ```without additionnal external exporter```?

**Comment by itcsoft54** [comment]
Php ftpm Status page on which hipages / php-fpm_exporter is based, have new format since php 8.1 :

from php documentation :

```
Query Parameters[ ¶](https://www.php.net/manual/fr/fpm.status.php#fpm.status.parameters)

The format of the status page output can be altered by specifying one of the following query parameters:

    html
    json
    openmetrics
    xml

Additional information can also be returned using the full query parameter.`
```

so you juste need to configure `fpm-status` page and to call the php-fpm to have php-fpm metric on openmetrics format :

e.g : `https://localhost/fpm-status?openmetrics&full`

look at https://www.php.net/manual/fr/migration81.new-features.php#migration81.new-features.fpm too.

**Comment by dmamchyts** [comment]
thank you very much
