### ISSUE TITLE
Using with k8s

### ISSUE THREAD

**Issue by Vandersteen** [hipages/php-fpm_exporter#69]
Dear, first of all. You guys did a really nice job here ! Thanks for making it available.

I was hoping you could give me some pointers on how I best use this exporter in k8s.

I have an application that has the following setup:

* A k8s service pointing towards a deployment
* A k8s deployment
* Each of these deployment's pods runs a php-fpm and a nginx container.

Using this exporter, should I add the exporter to every pod or do I run only 1 instance of the exporter and somehow (automatically when scaling up / down) point it towards every php-fpm instance.

I was thinking of running the exporter per pod.

But i'm not sure this is the right way to go ahead - any pointers would be appreciated

**Comment by estahn** [comment]
Hi @Vandersteen, we're running php-fpm_exporter as a sidecar. Every pod has a php-fpm_exporter with the following environment variables being set:

```
PHP_FPM_SCRAPE_URI: tcp://127.0.0.1:9000/status
PHP_FPM_FIX_PROCESS_COUNT: 1
```

We have to run Apache inside the pod, but we're looking at removing this constriction atm. Imo you should be able to only have `php-fpm` and `php-fpm_exporter` inside the pod and run ingress nginx (https://kubernetes.github.io/ingress-nginx/user-guide/fcgi-services/). We're going to experiment with this early next year.

If this works we may be able to centralise php-fpm_exporter, instead of running it as sidecar.

**Comment by estahn** [comment]
@Vandersteen I will close this issue. Feel free to re-open it if you have further questions.

**Comment by jonathanribas** [comment]
Hi @estahn, 
1/Are you still running php-fpm_exporter as a sidecar?
Any chance to run it separately?

2/ What CPU And memory ressources do you recommend for php-fpm_exporter?

Thanks in advance for your help!

**Comment by fwernert** [comment]
Hello,
Is it better to run hipages/php-fpm_exporter as a second container inside the deployment or use a specific deployment for hipages/php-fpm_exporter only?

And: 
2/ What CPU And memory ressources do you recommend for php-fpm_exporter?

Thank you.
